import React from 'react';
import { LegalPageLayout } from '../LegalPageLayout';
import { LegalSection } from '../LegalSection';
import { LegalNotice } from '../LegalNotice';
import { LEGAL_CONFIG } from '../../../constants/legal';
import { NavTab } from '../../../types';
import { Sparkles, Eye, Scissors, Camera, AlertTriangle } from 'lucide-react';

interface AiDisclaimerPageProps {
  onNavigate: (tab: NavTab) => void;
  onBack?: () => void;
}

export const AiDisclaimerPage: React.FC<AiDisclaimerPageProps> = ({ onNavigate, onBack }) => {
  return (
    <LegalPageLayout
      currentTab="ai-disclaimer"
      title="AI / Virtual Try-On Disclaimer"
      shortDescription="Important information regarding the synthetic nature, visual accuracy, and advisory role of computer-generated virtual fitting previews."
      onNavigate={onNavigate}
      onBack={onBack}
      badge="Advisory Notice"
    >
      <LegalNotice type="warning" title="Visual Approximation Only — Not a Guarantee of Physical Fit">
        Virtual Try-On results rendered by {LEGAL_CONFIG.APP_NAME} are generated by artificial intelligence. They represent a visual simulation of style, pattern, and color, and should not be relied upon as an exact or guaranteed representation of physical garment fit, size, or drape.
      </LegalNotice>

      {/* 1. Synthetic Nature of AI Try-On */}
      <LegalSection number="1" title="Synthetic Nature of AI Try-On Previews">
        <p>
          The virtual try-on images produced by this platform are generated using advanced neural networks and deep learning computer vision algorithms.
        </p>
        <p>
          These algorithms analyze the customer portrait and composite the selected garment onto the subject's pose and body contours. The resulting image is a digital rendering created for illustrative and retail styling purposes only.
        </p>
      </LegalSection>

      {/* 2. Key Limitations & Variances */}
      <LegalSection number="2" title="Variances from Physical Garments">
        <p>
          You and your customers should be aware that generated virtual fits may exhibit differences from physical garments in real life, including:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
          <div className="p-3.5 rounded-2xl bg-neutral-50 border border-neutral-200/80 space-y-1">
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-neutral-900">
              <Scissors className="w-4 h-4 text-emerald-600" />
              <span>Physical Fit & Tightness</span>
            </div>
            <p className="text-xs text-neutral-500">
              The AI cannot calculate fabric stretch, tension, bust/waist exact tailoring ease, or physical comfort.
            </p>
          </div>

          <div className="p-3.5 rounded-2xl bg-neutral-50 border border-neutral-200/80 space-y-1">
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-neutral-900">
              <Eye className="w-4 h-4 text-purple-600" />
              <span>Color & Texture Perception</span>
            </div>
            <p className="text-xs text-neutral-500">
              Screen calibration, digital lighting, sheen, and embroidery textures may look slightly different under natural store lighting.
            </p>
          </div>

          <div className="p-3.5 rounded-2xl bg-neutral-50 border border-neutral-200/80 space-y-1">
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-neutral-900">
              <Camera className="w-4 h-4 text-blue-600" />
              <span>Pose & Angle Factors</span>
            </div>
            <p className="text-xs text-neutral-500">
              Angle, resolution, and posture in the customer's photo significantly influence how realistic the garment drape looks.
            </p>
          </div>

          <div className="p-3.5 rounded-2xl bg-neutral-50 border border-neutral-200/80 space-y-1">
            <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-neutral-900">
              <AlertTriangle className="w-4 h-4 text-amber-600" />
              <span>Unstitched & Complex Drapes</span>
            </div>
            <p className="text-xs text-neutral-500">
              Unstitched fabric (e.g. traditional sarees or loose dupattas) cannot be realistically simulated by automated stitched garment engines.
            </p>
          </div>
        </div>
      </LegalSection>

      {/* 3. Recommended Use & Professional Judgment */}
      <LegalSection number="3" title="Role of Boutique Staff & Professional Judgment">
        <p>
          {LEGAL_CONFIG.APP_NAME} is intended as an empowering sales and consultation aid to help customers discover matching colors and styles quickly.
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Boutique staff should always guide customers with standard physical size charts and trial room fittings before final tailoring or purchase.</li>
          <li>Do not use AI previews to settle disputes regarding tailored alterations or bespoke sizing.</li>
        </ul>
      </LegalSection>

      {/* 4. Service Availability & Neural Model Dependency */}
      <LegalSection number="4" title="Infrastructure & Service Availability">
        <p>
          Virtual try-on generation utilizes cloud-based GPU infrastructure and external neural model APIs. While designed for high availability:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Processing times may fluctuate during peak periods.</li>
          <li>Generations may occasionally fail due to network disruptions or unsupported poses.</li>
          <li>In the event of a technical generation failure, consumed AI credits are automatically restored to the boutique balance.</li>
        </ul>
      </LegalSection>

      {/* 5. Questions */}
      <LegalSection number="5" title="Feedback & Inquiries">
        <p>
          If you encounter rendering anomalies or have questions regarding model capabilities, please contact our technical team at <strong>{LEGAL_CONFIG.SUPPORT_EMAIL}</strong>.
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
};
